#!/usr/bin/env python3
"""
Generate simple chess pieces as OBJ files (no Blender required)
OBJ is a text-based mesh format - we can generate it programmatically.

Usage: python3 generate_simple_pieces.py
"""

import os
import math
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "pieces" / "generated_basic"

# Piece dimensions in generic units (to be scaled later)
# These are simplified geometric representations

def write_obj(filepath, vertices, faces, normals=None, uvs=None):
    """Write an OBJ file from mesh data."""
    with open(filepath, 'w') as f:
        f.write("# Simple procedural chess piece\n")
        f.write(f"# Generated by generate_simple_pieces.py\n\n")
        
        # Write vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[2]:.6f} {v[1]:.6f}\n")  # OBJ uses Y-up, we use Z-up
        
        f.write(f"\n# {len(vertices)} vertices\n\n")
        
        # Write normals if provided
        if normals:
            for n in normals:
                f.write(f"vn {n[0]:.6f} {n[2]:.6f} {n[1]:.6f}\n")
        
        # Write UVs if provided
        if uvs:
            for uv in uvs:
                f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        
        # Write faces (1-indexed in OBJ)
        f.write(f"\n# {len(faces)} faces\n\n")
        for face in faces:
            if len(face) == 3:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
            elif len(face) == 4:
                f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1} {face[3]+1}\n")

def create_cylinder_vertices(radius, height, segments=16):
    """Create vertices for a cylinder."""
    vertices = []
    
    # Bottom circle
    for i in range(segments):
        angle = 2 * math.pi * i / segments
        x = radius * math.cos(angle)
        y = radius * math.sin(angle)
        vertices.append((x, y, 0))
    
    # Bottom center
    vertices.append((0, 0, 0))
    
    # Top circle
    for i in range(segments):
        angle = 2 * math.pi * i / segments
        x = radius * math.cos(angle)
        y = radius * math.sin(angle)
        vertices.append((x, y, height))
    
    # Top center
    vertices.append((0, 0, height))
    
    return vertices

def create_cylinder_faces(segments=16):
    """Create face indices for a cylinder."""
    faces = []
    bottom_center = segments
    top_center = 2 * segments + 1
    
    # Bottom faces
    for i in range(segments):
        next_i = (i + 1) % segments
        faces.append([i, next_i, bottom_center])
    
    # Top faces
    for i in range(segments):
        next_i = (i + 1) % segments
        faces.append([segments + i, top_center, segments + next_i])
    
    # Side faces (quads)
    for i in range(segments):
        next_i = (i + 1) % segments
        v0 = i
        v1 = next_i
        v2 = segments + next_i
        v3 = segments + i
        faces.append([v0, v1, v2, v3])
    
    return faces

def generate_king(output_path):
    """Generate a basic king piece."""
    vertices = []
    faces = []
    
    # Base
    base_r = 1.8
    base_h = 0.5
    
    # Body - wide cylinder
    body_r = 1.2
    body_h = 2.5
    
    # Neck
    neck_r = 0.8
    neck_h = 0.4
    
    # Head
    head_r = 1.0
    head_h = 1.0
    
    # We'll build this as stacked cylinders with different segment resolutions
    segments = 32
    
    # Simplified: single tapered cylinder for now
    v_base = create_cylinder_vertices(base_r, base_h, segments)
    f_base = create_cylinder_faces(segments)
    
    # Offset body to sit on base
    v_body = create_cylinder_vertices(body_r, body_h, segments)
    v_body = [(v[0], v[1], v[2] + base_h) for v in v_body]
    f_body = [[f + len(v_base) for f in face] for face in create_cylinder_faces(segments)]
    
    # Neck
    v_neck = create_cylinder_vertices(neck_r, neck_h, segments)
    v_neck = [(v[0], v[1], v[2] + base_h + body_h) for v in v_neck]
    f_neck = [[f + len(v_base) + len(v_body) for f in face] for face in create_cylinder_faces(segments)]
    
    # Head
    v_head = create_cylinder_vertices(head_r, head_h, segments)
    v_head = [(v[0], v[1], v[2] + base_h + body_h + neck_h) for v in v_head]
    f_head = [[f + len(v_base) + len(v_body) + len(v_neck) for f in face] for face in create_cylinder_faces(segments)]
    
    # Combine
    all_vertices = v_base + v_body + v_neck + v_head
    all_faces = f_base + f_body + f_neck + f_head
    
    write_obj(output_path, all_vertices, all_faces)

def generate_queen(output_path):
    """Generate a basic queen piece (similar to king but shorter)."""
    vertices = []
    
    # Simplified - use same cylinder approach with different proportions
    base_r = 1.8
    base_h = 0.5
    body_r = 1.2
    body_h = 2.0
    neck_r = 0.8
    neck_h = 0.3
    head_r = 1.1
    head_h = 0.8
    
    segments = 32
    
    v_base = create_cylinder_vertices(base_r, base_h, segments)
    v_body = create_cylinder_vertices(body_r, body_h, segments)
    v_body = [(v[0], v[1], v[2] + base_h) for v in v_body]
    v_neck = create_cylinder_vertices(neck_r, neck_h, segments)
    v_neck = [(v[0], v[1], v[2] + base_h + body_h) for v in v_neck]
    v_head = create_cylinder_vertices(head_r, head_h, segments)
    v_head = [(v[0], v[1], v[2] + base_h + body_h + neck_h) for v in v_head]
    
    # Add crown points (simplified as pyramid on top)
    crown_points = []
    crown_height = head_h + 0.6
    for i in range(4):
        angle = i * math.pi / 2 + math.pi / 4
        x = head_r * 0.6 * math.cos(angle)
        y = head_r * 0.6 * math.sin(angle)
        crown_points.append((x, y, crown_height))
    
    all_vertices = v_base + v_body + v_neck + v_head + crown_points
    
    # Basic faces (simplified - just the cylinders for now)
    f_base = create_cylinder_faces(segments)
    f_body = [[f + len(v_base) for f in face] for face in create_cylinder_faces(segments)]
    f_neck = [[f + len(v_base) + len(v_body) for f in face] for face in create_cylinder_faces(segments)]
    f_head = [[f + len(v_base) + len(v_body) + len(v_neck) for f in face] for face in create_cylinder_faces(segments)]
    
    all_faces = f_base + f_body + f_neck + f_head
    
    write_obj(output_path, all_vertices, all_faces)

def generate_rook(output_path):
    """Generate a rook piece (castle/cylindrical)."""
    base_r = 1.8
    base_h = 0.5
    body_r = 1.5
    body_h = 2.5
    top_r = 1.6
    top_h = 0.6
    
    segments = 32
    
    v_base = create_cylinder_vertices(base_r, base_h, segments)
    v_body = create_cylinder_vertices(body_r, body_h, segments)
    v_body = [(v[0], v[1], v[2] + base_h) for v in v_body]
    v_top = create_cylinder_vertices(top_r, top_h, segments)
    v_top = [(v[0], v[1], v[2] + base_h + body_h) for v in v_top]
    
    all_vertices = v_base + v_body + v_top
    
    f_base = create_cylinder_faces(segments)
    f_body = [[f + len(v_base) for f in face] for face in create_cylinder_faces(segments)]
    f_top = [[f + len(v_base) + len(v_body) for f in face] for face in create_cylinder_faces(segments)]
    
    all_faces = f_base + f_body + f_top
    
    write_obj(output_path, all_vertices, all_faces)

def generate_bishop(output_path):
    """Generate a bishop piece (slit head)."""
    base_r = 1.8
    base_h = 0.5
    body_r = 1.1
    body_h = 2.2
    head_r = 1.2
    head_h = 0.9
    
    segments = 32
    
    v_base = create_cylinder_vertices(base_r, base_h, segments)
    v_body = create_cylinder_vertices(body_r, body_h, segments)
    v_body = [(v[0], v[1], v[2] + base_h) for v in v_body]
    
    # Oval head (scaled cylinder)
    v_head = create_cylinder_vertices(head_r, head_h, segments)
    v_head = [(v[0] * 1.0, v[1] * 1.3, v[2] + base_h + body_h) for v in v_head]
    
    all_vertices = v_base + v_body + v_head
    
    f_base = create_cylinder_faces(segments)
    f_body = [[f + len(v_base) for f in face] for face in create_cylinder_faces(segments)]
    f_head = [[f + len(v_base) + len(v_body) for f in face] for face in create_cylinder_faces(segments)]
    
    all_faces = f_base + f_body + f_head
    
    write_obj(output_path, all_vertices, all_faces)

def generate_knight(output_path):
    """Generate a knight piece (simplified horse head)."""
    base_r = 1.8
    base_h = 0.5
    body_r = 1.1
    body_h = 1.8
    head_r = 1.0
    head_h = 1.0
    
    segments = 32
    
    v_base = create_cylinder_vertices(base_r, base_h, segments)
    v_body = create_cylinder_vertices(body_r, body_h, segments)
    v_body = [(v[0], v[1], v[2] + base_h) for v in v_body]
    
    # Horse head (tilted cone)
    v_head = create_cylinder_vertices(head_r * 0.6, head_h, segments)
    v_head = [(v[0], v[1] + 0.3, v[2] + base_h + body_h) for v in v_head]
    
    all_vertices = v_base + v_body + v_head
    
    f_base = create_cylinder_faces(segments)
    f_body = [[f + len(v_base) for f in face] for face in create_cylinder_faces(segments)]
    f_head = [[f + len(v_base) + len(v_body) for f in face] for face in create_cylinder_faces(segments)]
    
    all_faces = f_base + f_body + f_head
    
    write_obj(output_path, all_vertices, all_faces)

def generate_pawn(output_path):
    """Generate a pawn piece (simple ball top)."""
    base_r = 1.6
    base_h = 0.4
    body_r = 0.9
    body_h = 1.5
    head_r = 1.0
    head_h = 0.8
    
    segments = 24
    
    v_base = create_cylinder_vertices(base_r, base_h, segments)
    v_body = create_cylinder_vertices(body_r, body_h, segments)
    v_body = [(v[0], v[1], v[2] + base_h) for v in v_body]
    v_head = create_cylinder_vertices(head_r, head_h, segments)
    v_head = [(v[0], v[1], v[2] + base_h + body_h) for v in v_head]
    
    all_vertices = v_base + v_body + v_head
    
    f_base = create_cylinder_faces(segments)
    f_body = [[f + len(v_base) for f in face] for face in create_cylinder_faces(segments)]
    f_head = [[f + len(v_base) + len(v_body) for f in face] for face in create_cylinder_faces(segments)]
    
    all_faces = f_base + f_body + f_head
    
    write_obj(output_path, all_vertices, all_faces)

def main():
    """Generate all chess pieces."""
    
    print("=== Simple Chess Piece Generator ===")
    print(f"Output directory: {OUTPUT_DIR}")
    
    # Create output directories
    white_dir = OUTPUT_DIR / "white"
    black_dir = OUTPUT_DIR / "black"
    white_dir.mkdir(parents=True, exist_ok=True)
    black_dir.mkdir(parents=True, exist_ok=True)
    
    pieces = ['king', 'queen', 'rook', 'bishop', 'knight', 'pawn']
    
    print("\nGenerating pieces...")
    
    for piece in pieces:
        print(f"  Creating {piece}...")
        
        if piece == 'king':
            func = generate_king
        elif piece == 'queen':
            func = generate_queen
        elif piece == 'rook':
            func = generate_rook
        elif piece == 'bishop':
            func = generate_bishop
        elif piece == 'knight':
            func = generate_knight
        else:  # pawn
            func = generate_pawn
        
        # Generate both colors (same geometry, materials differ)
        white_path = white_dir / f"{piece}.obj"
        black_path = black_dir / f"{piece}.obj"
        
        func(str(white_path))
        func(str(black_path))
        
        print(f"    ✓ {white_path}")
        print(f"    ✓ {black_path}")
    
    print("\n=== Complete ===")
    print(f"Generated {len(pieces) * 2} OBJ files in {OUTPUT_DIR}")
    print("\nNote: These are simplified geometric pieces.")
    print("For higher quality, download detailed scanned models.")
    print("These are sufficient for initial pipeline testing.")
    print("\nColor is handled by materials, not geometry.")

if __name__ == "__main__":
    main()